### ISSUE TITLE
Overall Permissions Handling

### ISSUE THREAD

**Issue by AmaVic** [AmaVic/BMerode-Generator#22]
### Event-Participant Table
Defines which Business Event can be fired by which Business Object (Participant) Type.
Default: not allowed.

| Business Object Type | Business Event | Allowed |
| :--------------------: | :--------------: | :-------: |
| BOT1 | EVT1 | true |
| BOT1 | EVT2 | false |
| BOT2 | EVT1 | false |
| BOT2 | EVT2 | true |

#### markCollaborationAsReady
Once the setup of the collaboration is ready (required participants (BO) have been added), the _ParticipantsHandler_ can specify it using this transaction.

#### handleEvent
Upon reception of a request to handle a Business Event, the following checks must be performed:
* Check if the collaboration is marked as ready
  * if the collaboration is _not_ ready
    * check if the sender is the _ParticipantsHandler_ and _reject_ the request if that's not the case
    * if the sender is the _ParticipantsHandler_, then check if the Business Event is about CRU of a _Participant_ Business Object
      * if this is the case, then the event is accepted
      * if not, the event is rejected 
  * if the collaboration _is_ ready
    * fetch the business object that is linked to the sender's public key
    * check in the _Event-Participant Table_ whether the fired event is allowed for that type of participant
    * warning: Instance Access Rules are not implemented at this stage

##### Implications for implementation

- [x] The Event-Participant Table must be stored in the .mxp file ([see issue](https://github.com/AmaVic/BMerode-Generator/issues/23))
- [x] The Event-Participant Table must be generated as part of the smart contract (_for now_) ([see issue](https://github.com/AmaVic/BMerode-Generator/issues/24))
- [x] For each Participant Business Object, a _public key_ attribute must be stored ([see issue](https://github.com/AmaVic/BMerode-Generator/issues/19))
